spring.application.name=delivery

# H2 Database
spring.datasource.url=jdbc:h2:mem:deliverydb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# CronJob - runs every hour at HH:15:00
weather.import.cron=0 15 * * * *